INSERT INTO m_jenis_pengajuan_dokumen (id,keterangan,nama) VALUES
('1','JPG/PDF','File Surat Pengantar dari Pimpinan PT'),
('2','JPG/PDF','File Ijasah (Disertai Akreditasi Prodi; Penyetaraan Ijazah (untuk lulusan luar negeri))'),
('3','PDF','File Ringkasan Disertai/Tesis (sesuai pendidikan terakhir'),
('4','JPG/PDF','File Surat Bebas Tugas (Bila Ada)'),
('5','JPG/PDF','File Surat Pengaktifan Kembali (Bila Ada)'),
('6','JPG/PDF','File Rekap DUPAK (keseluruhan)'),
('8','JPG/PDF','File SK PAK Sebelumnya'),
('9','JPG/PDF','File SK Jabatan Terakhir'),
('10','PDF','File PPKP (DP3) 2 Tahun Terakhir'),
('11','JPG/PDF','File SK Pangkat Terakhir'),
('12','JPG/PDF','File Surat Keterangan Melaksanakan Penelitian'),
('15','JPG/PDF','File Persetujuan/Pertimbangan Senat'),
('16','JPG/PDF','File Daftar Hadir Anggota Senat PT'),
('17','JPG/PDF','File Surat Pernyataan Pengesahan hasil Validasi Karya Ilmiah'),
('18','JPG/PDF','File Surat Pernyataan Keabsahan Karya Ilmiah'),
('19','JPG/PDF','File Sertifikat Pendidik'),
('20','PDF','File Peer Review Per Unsur/Artikel Ilmiah/Dokumen/Buku berkaitan dengan No.21'),
('21','Excel/Word','Daftar Profil Penelitian (Judul,ISBN,Penerbit,jml.halaman) dan Link Buku/dokumen/Penelitian');
