INSERT INTO `dosen` VALUES ('5d9b24ff-21d9-44d6-8781-d6b5254c6bd2', 'Dosen 1');
INSERT INTO `dosen` VALUES ('47a1b8e8-fc1f-4082-8dea-6fa7a4899bbd', 'Dosen 2');

INSERT INTO `jenis_surat` VALUES ('6a20627f-65db-4a40-b92f-c575daaef370', 'SK Mengajar', 'SK Tugas Mengajar Mata Kuliah', 'Template Jenis Surat 1');
INSERT INTO `jenis_surat` VALUES ('af6d73bb-cf8e-4c47-be1c-9a93bc1f1e21', 'SK Bimbingan', 'SK Tugas Membimbing Skripsi', 'Template Jenis Surat 2');

INSERT INTO `surat_tugas` VALUES ('4fd3cf54-77dc-4523-9bab-36387987d99e', '123', '6a20627f-65db-4a40-b92f-c575daaef370',
                                  '5d9b24ff-21d9-44d6-8781-d6b5254c6bd2', '2017-04-14', '2017-04-15');
INSERT INTO `surat_tugas` VALUES ('5118e180-7055-4fc7-8394-e287b405840c', '321', 'af6d73bb-cf8e-4c47-be1c-9a93bc1f1e21',
                                  '47a1b8e8-fc1f-4082-8dea-6fa7a4899bbd', '2017-04-16', '2017-04-17');

INSERT INTO `jabatan` VALUES ('1', 'Asisten Ahli', 'Asisten ahli');
INSERT INTO `jabatan` VALUES ('2', 'Lektor', 'Lektor');
INSERT INTO `jabatan` VALUES ('3', 'Lektor Kepala', 'Lektor Kepala');
INSERT INTO `jabatan` VALUES ('4', 'Profesor', 'Profesor');
INSERT INTO `jabatan` VALUES ('5', 'Dokter', 'Dokter');

INSERT INTO `kategori_kegiatan` VALUES ('1', 'Pendidikan', 'Pendidikan');
INSERT INTO `kategori_kegiatan` VALUES ('2', 'Penelitian', 'Penelitian');
INSERT INTO `kategori_kegiatan` VALUES ('3', 'Pengabdian Masyarakat', 'Pengabdian Masyarakat');
INSERT INTO `kategori_kegiatan` VALUES ('4', 'Penunjang', 'Penunjang');

INSERT INTO `kategori_bukti_kegiatan` VALUES ('1', 'Bukti Pendidikan', 'Bukti Pendidikan');
INSERT INTO `kategori_bukti_kegiatan` VALUES ('2', 'Bukti Penelitian', 'Bukti Penelitian');
INSERT INTO `kategori_bukti_kegiatan` VALUES ('3', 'Bukti Pengabdian Masyarakat', 'Bukti Pengabdian Masyarakat');

INSERT INTO `jenis_kegiatan` VALUES ('1', 'I.A.1.a', 'Mengikuti pendidikan formal dan memperoleh gelar/sebutan/ijazah : Doktor / sederajat', 'Bukti tugas/izin belajar dan pindai ijazah asli', '1/periode penilaian', '200');
INSERT INTO `jenis_kegiatan` VALUES ('2', 'I.A.1.b', 'Mengikuti pendidikan formal dan memperoleh gelar/sebutan/ijazah : Magister/sederajat', 'Bukti tugas/izin belajar dan pindai ijazah asli', '1/periode penilaian', '150');
INSERT INTO `jenis_kegiatan` VALUES ('3', 'I.A.2 ', 'Mengikuti diklat prajabatan golongan III', 'Bukti tugas/izin belajar dan pindai ijazah asli', '1/periode penilaian', '3');
INSERT INTO `jenis_kegiatan` VALUES ('4', 'II.A.1.a ', 'Asisten Ahli untuk : beban mengajar 10 sks pertama ', 'Pindai SK penugasan asli dan bukti kinerja', '5', '0,5');
INSERT INTO `jenis_kegiatan` VALUES ('5', 'II.A.1.b ', 'Asisten Ahli untuk : beban mengajar 2 sks berikutnya', 'Pindai SK penugasan asli dan bukti kinerja', '0,5', '0,25');
INSERT INTO `jenis_kegiatan` VALUES ('6', 'II.A.2.a', 'Lektor/Lektor Kepala/Profesor untuk : beban mengajar 10 sks pertama', 'Pindai SK penugasan asli dan bukti kinerja', '10/semester', '1');
INSERT INTO `jenis_kegiatan` VALUES ('7', 'II.A.2.b ', 'Lektor/Lektor Kepala/Profesor untuk : beban mengajar 2 sks berikutnya ', 'Pindai SK penugasan asli dan bukti kinerja', '1/semester', '0,5');
INSERT INTO `jenis_kegiatan` VALUES ('8','II.A.3.a ', 'Kegiatan pelaksanaan pendidikan untuk pendidikan dokter klinis - Melakukan pengajaran untuk peserta   pendidikan dokter melalui tindakan medik spesialistik', 'Pindai SK Penugasan dan bukti kinerja', '11/semester', '4');
INSERT INTO `jenis_kegiatan` VALUES ('9', 'II.A.3.b ', 'Kegiatan pelaksanaan pendidikan untuk pendidikan dokter klinis - Melakukan pengajaran   Konsultasi spesialis  kepada peserta   pendidikan dokter ', 'Pindai SK Penugasan dan bukti kinerja', '11/semester', '2');
INSERT INTO `jenis_kegiatan` VALUES ('10', 'II.A.3.c ', 'Kegiatan pelaksanaan pendidikan untuk pendidikan dokter klinis - Melakukan pemeriksaan luar dengan pembimbingan terhadap peserta   pendidikan dokter ', 'Pindai SK Penugasan dan bukti kinerja', '11/semester', '2');
INSERT INTO `jenis_kegiatan` VALUES ('11', 'II.A.3.d ', 'Kegiatan pelaksanaan pendidikan untuk pendidikan dokter klinis - Melakukan pemeriksaan dalam dengan pembimbingan terhadap peserta   pendidikan dokter ', 'Pindai SK Penugasan dan bukti kinerja', '11/semester', '3');
INSERT INTO `jenis_kegiatan` VALUES ('12', 'II.A.3.e ', 'Kegiatan pelaksanaan pendidikan untuk pendidikan dokter klinis - Menjadi saksi ahli dengan  pembimbingan terhadap peserta pendidikan dokter ', 'Pindai SK Penugasan dan bukti kinerja', '11/semester', '1');
INSERT INTO `jenis_kegiatan` VALUES ('13', 'II.B ', 'Membimbing seminar mahasiswa (setiap mahasiswa)', 'Pindai SK penugasan asli dan bukti kinerja', '', '1');
INSERT INTO `jenis_kegiatan` VALUES ('14', 'II.C ', 'Membimbing KKN, Praktik Kerja Nyata, Praktik Kerja Lapangan (setiap semester) ', 'Pindai SK penugasan asli dan bukti kinerja', '', '1');
INSERT INTO `jenis_kegiatan` VALUES ('15', 'II.D.1.a', 'Pembimbing Utama per orang (setiap mahasiswa) - Disertasi', 'Pindai lembar pengesahan dan bukti kinerja', '4 lulusan/semester', '8');
INSERT INTO `jenis_kegiatan` VALUES ('16', 'II.D.1.b', 'Pembimbing Utama per orang (setiap mahasiswa) - Tesis', 'Pindai lembar pengesahan dan bukti kinerja', '6 lulusan/semester', '3');
INSERT INTO `jenis_kegiatan` VALUES ('17', 'II.D.1.c ', 'Pembimbing Utama per orang (setiap mahasiswa) - Skripsi', 'Pindai lembar pengesahan dan bukti kinerja', '8 lulusan/semester', '1');
INSERT INTO `jenis_kegiatan` VALUES ('18','II.D.1.d', 'Pembimbing Utama per orang (setiap mahasiswa) - Laporan akhir studi', 'Pindai lembar pengesahan dan bukti kinerja', '10 lulusan/semester', '1');
INSERT INTO `jenis_kegiatan` VALUES ('19', 'II.D.2.a', 'Pembimbing Pendamping/Pembantu per orang (setiap mahasiswa) : Disertasi', 'Pindai lembar pengesahan dan bukti kinerja', '4 lulusan/semester', '6');
INSERT INTO `jenis_kegiatan` VALUES ('20', 'II.D.2.b', 'Pembimbing Pendamping/Pembantu per orang (setiap mahasiswa) : Tesis ', 'Pindai lembar pengesahan dan bukti kinerja', '6 lulusan/semester', '2');
INSERT INTO `jenis_kegiatan` VALUES ('21', 'II.D.2.c', 'Pembimbing Pendamping/Pembantu per orang (setiap mahasiswa) : Skripsi ', 'Pindai lembar pengesahan dan bukti kinerja', '8 lulusan/semester', '0,5');
INSERT INTO `jenis_kegiatan` VALUES ('22', 'II.D.2.d', 'Pembimbing Pendamping/Pembantu per orang (setiap mahasiswa) : Laporan akhir studi ', 'Pindai lembar pengesahan dan bukti kinerja', '10 lulusan/semester', '0,5');
INSERT INTO `jenis_kegiatan` VALUES ('23', 'II.E.1 ', 'Bertugas sebagai penguji pada ujian akhir/Profesi*** (setiap mahasiswa) : Ketua penguji', 'Pindai SK penugasan, bukti kinerja dan undangan', '4 lulusan/semester', '1');
INSERT INTO `jenis_kegiatan` VALUES ('24', 'II.E.2', 'Bertugas sebagai penguji pada ujian akhir/Profesi*** (setiap mahasiswa) : Anggota penguji ', 'Pindai SK penugasan, bukti kinerja dan undangan', '8 lulusan/semester', '0,5');
INSERT INTO `jenis_kegiatan` VALUES ('25', 'II.F ', 'Membina kegiatan mahasiswa di bidang akademik dan kemahasiswaan, termasuk dalam kegiatan ini adalah membimbing mahasiswa menghasilkan produk saintifik (setiap semester)', 'Pindai SK penugasan, dan bukti kinerja', '2 kegiatan/semester', '1');
INSERT INTO `jenis_kegiatan` VALUES ('26', 'II.G ', 'Mengembangkan program kuliah yang mempunyai nilai kebaharuan metode atau substansi (setiap produk) ', 'File produk', '1 mata kuliah/semester', '2');
INSERT INTO `jenis_kegiatan` VALUES ('27', 'II.H.1', 'Mengembangkan bahan pengajaran/ bahan kuliah yang mempunyai nilai kebaharuan (setiap produk), Buku ajar ', 'File produk', '1 buku/tahun', '20');
INSERT INTO `jenis_kegiatan` VALUES ('28', 'II.H.2 ', 'Mengembangkan bahan pengajaran/ bahan kuliah yang mempunyai nilai kebaharuan (setiap produk), Diktat,Modul, Petunjuk praktikum,      Model, Alat bantu, Audio visual, Naskah tutorial, Job sheet praktikum terkait dengan mata kuliah yang diampu ', 'File produk', '1 Produk/semester', '5');
INSERT INTO `jenis_kegiatan` VALUES ('29', 'II.I ', 'Menyampaikan orasi ilmiah di tingkat perguruan tinggi ', 'File produk', '2 orasi/semester', '5');
INSERT INTO `jenis_kegiatan` VALUES ('30', 'II.J.1 ', 'Menduduki jabatan pimpinan perguruan tinggi (setiap semester) : Rektor ', 'Pindai SK Jabatan', '1 Jabatan/semester', '6');
INSERT INTO `jenis_kegiatan` VALUES ('31', 'II.J.2', 'Menduduki jabatan pimpinan perguruan tinggi (setiap semester) : Wakil rektor/dekan/direktur program pasca sarjana/ketua lembaga ', 'Pindai SK Jabatan', '1 Jabatan/semester', '5');
INSERT INTO `jenis_kegiatan` VALUES ('32', 'II.J.3', 'Menduduki jabatan pimpinan perguruan tinggi (setiap semester) : Ketua sekolah tinggi/pembantu dekan/asisten direktur program pasca sarjana/direktur politeknik/koordinator kopertis ', 'Pindai SK Jabatan', '1 Jabatan/semester', '4');
INSERT INTO `jenis_kegiatan` VALUES ('33', 'II.J.4', 'Menduduki jabatan pimpinan perguruan tinggi (setiap semester) : Pembantu ketua sekolah tinggi/pembantu direktur politeknik', 'Pindai SK Jabatan', '1 Jabatan/semester', '4');
INSERT INTO `jenis_kegiatan` VALUES ('34', 'II.J.5', 'Menduduki jabatan pimpinan perguruan tinggi (setiap semester) : Direktur akademi ', 'Pindai SK Jabatan', '1 Jabatan/semester', '4');
INSERT INTO `jenis_kegiatan` VALUES ('35', 'II.J.6', 'Menduduki jabatan pimpinan perguruan tinggi (setiap semester) : Pembantu direktur politeknik, ketua jurusan/ bagian pada universitas/ institut/sekolah tinggi', 'Pindai SK Jabatan', '1 Jabatan/semester', '3');
INSERT INTO `jenis_kegiatan` VALUES ('36', 'II.J.7', 'Menduduki jabatan pimpinan perguruan tinggi (setiap semester) : Pembantu direktur akademi/ketua jurusan/ketua prodi pada universitas/politeknik/akademi, sekretaris jurusan/bagian pada universitas/institut/sekolah tinggi ', 'Pindai SK Jabatan', '1 Jabatan/semester', '3');
INSERT INTO `jenis_kegiatan` VALUES ('37', 'II.J.8', 'Menduduki jabatan pimpinan perguruan tinggi (setiap semester) : Sekretaris jurusan pada politeknik/akademi dan kepala laboratorium (bengkel) universitas/institut/sekolah tinggi/politeknik/akademi ', 'Pindai SK Jabatan', '1 Jabatan/semester', '3');
INSERT INTO `jenis_kegiatan` VALUES ('38', 'II.K.1 ', 'Membimbing dosen yang mempunyai jabatan akademik lebih rendah setiap semester (bagi dosen Lektor Kepala ke atas) : Pembimbing pencangkokan ', 'Pindai SK Penugasan, dan bukti kinerja', '1 orang', '2');
INSERT INTO `jenis_kegiatan` VALUES ('39', 'II.K.2 ', 'Membimbing dosen yang mempunyai jabatan akademik lebih rendah setiap semester (bagi dosen Lektor Kepala ke atas) : Reguler', 'Pindai SK Penugasan, dan bukti kinerja', '1 orang', '1');
INSERT INTO `jenis_kegiatan` VALUES ('40', 'II.L.1', 'Melaksanakan kegiatan detasering dan pencangkokan di luar institusi tempat bekerja setiap semester (bagi dosen Lektor kepala ke atas) : Detasering', 'Pindai SK Penugasan, dan bukti kinerja', '1 orang', '5');
INSERT INTO `jenis_kegiatan` VALUES ('41', 'II.L.2', 'Melaksanakan kegiatan detasering dan pencangkokan di luar institusi tempat bekerja setiap semester (bagi dosen Lektor kepala ke atas) : Pencangkokan', 'Pindai SK Penugasan, dan bukti kinerja', '1 orang', '4');
INSERT INTO `jenis_kegiatan` VALUES ('42', 'II.M.1', 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya lebih dari 960 jam', 'Pindai sertifikat asli', '', '15');
INSERT INTO `jenis_kegiatan` VALUES ('43', 'II.M.2', 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara  641- 960 jam', 'Pindai sertifikat asli', '', '9');
INSERT INTO `jenis_kegiatan` VALUES ('44', 'II.M.3', 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara 481- 640 jam ', 'Pindai sertifikat asli', '', '6');
INSERT INTO `jenis_kegiatan` VALUES ('45', 'II.M.4', 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara 161- 480 jam ', 'Pindai sertifikat asli', '', '3');
INSERT INTO `jenis_kegiatan` VALUES ('46', 'II.M.5', 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara   81- 160 jam', 'Pindai sertifikat asli', '', '2');
INSERT INTO `jenis_kegiatan` VALUES ('47', 'II.M.6', 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara 30 - 80 jam ', 'Pindai sertifikat asli', '', '1');
INSERT INTO `jenis_kegiatan` VALUES ('48', 'II.M.7', 'Melaksanakan pengembangan diri untuk meningkatkan kompetensi : Lamanya antara 10 - 30 jam ', 'Pindai sertifikat asli', '', '0,5');

INSERT INTO `mata_kuliah` VALUES('1', '1','General Arabic','Matrikulasi','0','0');
INSERT INTO `mata_kuliah` VALUES('2', '2','General English','Matrikulasi','0','0');
INSERT INTO `mata_kuliah` VALUES('3', 'AEM1101','Dirasah Islamiah','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('4', 'AEM1201','Bahasa Inggris Ekonomi','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('5', 'MKK-U08','Statistik I','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('6', 'AEM1202','Bahasa Indonesia','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('7', 'AEM1301','Matematika Ekonomi','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('8', 'MGT1207','Pengantar Bisnis dan Manajemen','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('9', 'AEM1401','Pengantar Aplikasi Komputer','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('10', 'AEM1401','Pengantar Ekonomi','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('11', 'MKK-U10','Pengantar Fiqh Muamalah','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('12', 'MKK-U15','Pengantar Ekonomi Makro','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('13', 'MKK-U16','Pengantar Komputer','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('14', 'MKK-U14','Pengantar Ekonomi Mikro','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('15', 'TJA','Tahfidz Juz','Matrikulasi','0','0');
INSERT INTO `mata_kuliah` VALUES('16', 'AEM1102','Sejarah Peradaban & Kepemimpinan Islam','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('17', 'AEM1203','Bahasa Arab Ekonomi','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('18', 'MKK-U01','Bahasa Arab I','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('19', 'AEM1302','Statistika Ekonomi & Bisnis','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('20', 'ACC1101','Pengantar Akuntansi I','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('21', 'AEM1103','Fiqh Muamalah I','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('22', 'MKK-U07','Matematika Ekonomi II','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('23', 'MKK-U09','Statistika II','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('24', 'AEM1104','Ayat & Hadits Ekonomi','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('25', 'MKK-U04','Bahasa Inggris II','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('26', 'AEM1402','Kewarganegaraan','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('27', 'MKK-U02','Bahasa Arab II','Matrikulasi','0','2');
INSERT INTO `mata_kuliah` VALUES('28', 'AEM2105','Ushul Fiqh I','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('29', 'AEM2303','Bank & Lembaga Keuangan','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('30', 'AEM2304','Ekonometrik Dasar','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('31', 'AEM2106','Fiqh Muamalah II','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('32', 'ACC2102','Pengantar Akuntansi II','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('33', 'AEM2305','Aspek Hukum Dalam Ekonomi','Bisnis Dan Manajemen Islam','','2');
INSERT INTO `mata_kuliah` VALUES('34', 'AEM2204','Bahasa Inggris Akademik','Bisnis Dan Manajemen Islam','','1');
INSERT INTO `mata_kuliah` VALUES('35', 'AEM3301','Matematika Keuangan Dan Bisnis','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('36', 'ACC2701','Etika Bisnis Islam','Bisnis Dan Manajemen Islam','','2');
INSERT INTO `mata_kuliah` VALUES('37', 'ECO2203','Teori Ekonomi Mikro I','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('38', 'AEM2107','Ushul Fiqh II','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('39', 'AEM2108','Fiqh Mawarist','Bisnis Dan Manajemen Islam','','2');
INSERT INTO `mata_kuliah` VALUES('40', 'MKK-U18','Metode Kuantitatif','Bisnis Dan Manajemen Islam','','2');
INSERT INTO `mata_kuliah` VALUES('41', 'AEM2109','Studi Kepemimpinan Islam','Bisnis Dan Manajemen Islam','','2');
INSERT INTO `mata_kuliah` VALUES('42', 'AEM2110','Fundamental Ekonomi Islam','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('43', 'FIN2301','Manajemen Keuangan','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('44', 'ECO2201','Teori Ekonomi Makro I','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('45', 'ACC2201','Akuntansi Biaya','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('46', 'ENT3601','Kewirausahaan I','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('47', 'AEM3111','Fiqh Zakat','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('48', 'AEM3306','Lab Mini Bank Syariah','Bisnis Dan Manajemen Islam','','2');
INSERT INTO `mata_kuliah` VALUES('49', 'MGT3102','Sistem Informasi Manajemen','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('50', 'IFI3401','Manajemen Perbankan Islam I','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('51', 'MKJ-K02','Manajemen Perbankan Syariah I','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('52', 'BIS3203','Manajemen Operasi','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('53', 'BIS3202','Bisnis Internasional','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('54', 'ACC3501','Akuntansi Lembaga Keuangan Syariah','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('55', 'BIS3204','Perilaku Organisasi','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('56', 'IFI3402','Manajemen Lembaga Keuangan Syariah','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('57', 'MGT3301','Manajemen Pemasaran','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('58', 'MGT3101','Metode Penelitian Bisnis','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('59', 'MGT3103','Manajemen Investasi','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('60', 'FIN3302','Manajemen Keuangan Lanjutan','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('61', 'MGT4105','Manajemen Strategi','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('62', 'MKP-P-3706','Manajemen Pemasaran Bank Syariah','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('63', 'MKJ-U04','Manajemen Pemasaran Jasa','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('64', 'MKK-P12','Pemasaran Stratejik','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('65', 'MKP-P-3602','Manajemen Pemasaran Syariah','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('66', 'IFI3403','Manajemen Keuangan Islam','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('67', 'MGT3303','Pemasaran Internasional','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('68', 'MKP-K-3603','Manajemen Keuangan Syariah','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('69', 'ACC3202','Akuntansi Manajemen','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('70', 'MKJ-P08','Manajemen Produk Dan Harga','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('71', 'AEM3205','Fahmul Maqruq','Bisnis Dan Manajemen Islam','','1');
INSERT INTO `mata_kuliah` VALUES('72', 'MKJ-K03','Manajemen Asuransi Syariah','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('73', 'BIS3201','Magang','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('74', 'IFI4404','Manajemen Perbankan Islam II','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('75', 'MKT4503','Riset Pemasaran & Studi Kelayakan Bisnis','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('76', 'MKJ-K11','Manajemen Perbankan Syariah II','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('77', 'IFI4303','Manajemen Keuangan Internasional','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('78', 'MKT4504','Komunikasi Pemasaran','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('79', 'MKJ-K05','Keuangan Internasional','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('80', 'MGT4309','Manajemen Produk dan Harga','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('81', 'IFI4405','Pasar & Instr. Keuangan Islam','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('82', 'MGT4306','Strategi Kewirausahaan','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('83', 'MKJ-U06','Manajemen Internasional','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('84', 'FIN4305','Manajemen Resiko Keuangan','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('85', 'MKJ-K12','Manajemen Resiko Pembiayaan','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('86', 'BIS4206','Studi Kelayakan Bisnis','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('87', 'FIN4304','Seminar Keuangan & Perbankan','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('88', 'ENT4607','Seminar Pemasaran & Kewirausahaan','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('89', 'MKB-U16','Ekonomi Manajerial','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('90', 'MGT3401','Manajemen Pemasaran Islam','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('91', 'MKB-U13','Penganggaran Perusahaan','Bisnis Dan Manajemen Islam','','2');
INSERT INTO `mata_kuliah` VALUES('92', 'FIN4104','Manajemen Sumber Daya Insani','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('93', 'MKJ-P07','Manajemen Inovasi&Kreativitas','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('94', 'MKB-U13','Manjemen Penganggaran','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('95', 'MKB-U17','Teori Pengambilan Keputusan','Bisnis Dan Manajemen Islam','','3');
INSERT INTO `mata_kuliah` VALUES('96', 'MGT4107','Skripsi','Bisnis Dan Manajemen Islam','','6');
INSERT INTO `mata_kuliah` VALUES('97', 'AEM2105','Usul Fiqh I','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('98', 'AEM2303','Bank & Lembaga Keuangan','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('99', 'AEM2304','Applied Statistics','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('100', 'AEM2106','Fiqh Muamalah II','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('101', 'ACC2102','Pengantar Akuntansi II','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('102', 'AEM2305','Aspek Hukum Dalam Ekonomi','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('103', 'AEM2204','Bahasa Inggris Akademik','Akuntansi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('104', 'ACC2701','Etika Bisnis Islam','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('105', 'ACC2401','Perpajakan I','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('106', 'AEM2107','Ushul Fiqh II','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('107', 'AEM2108','Fiqh Mawarist','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('108', 'AEM2109','Studi Kepemimpinan Islam','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('109', 'AEM2110','Fundamental Ekonomi Islam','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('110', 'FIN2301','Manajemen Keuangan','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('111', 'ACC2103','Akuntansi Keuangan I','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('112', 'ACC2201','Akuntansi Biaya','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('113', 'ENT3601','Kewirausahaan I','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('114', 'AEM3111','Fiqh Zakat','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('115', 'AEM3306','Lab Mini Bank Islam','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('116', 'ACC3403','Akuntansi Sektor Publik','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('117', 'ACC3802','Laboratorium Akuntansi','Akuntansi Islam','1','3');
INSERT INTO `mata_kuliah` VALUES('118', 'ACC3104','Akuntansi Keuangan II','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('119', 'ACC3501','Akuntansi Lembaga Keuangan Syariah','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('120', 'ACC3901','Sistem Informasi Akuntansi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('121', 'ENT3102','Sistem Informasi Manajemen','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('122', 'ACC3601','Akuntansi Zakat','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('123', 'ACC3105','Teori Akuntansi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('124', 'ACC3202','Akuntansi Manajemen','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('125', 'ACC3106','Akuntansi Keuangan Lanjutan','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('126', 'ACC3402','Perpajakan II','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('127', 'ACC3301','Auditing I','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('128', 'AEM3205','Fahmul Maqruq','Akuntansi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('129', 'ACC3102','Magang','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('130', 'MKK-A-3720','Lab Audit','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('131', 'MKK-A-3710','Lab. Pemeriksaan Akuntansi II','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('132', 'ACC4904','Network Based Accounting Information Systems I','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('133', 'MKJ-A04','Akuntansi Keuangan Lanjutan II','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('134', 'ACC4108','Akuntansi Islam','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('135', 'ACC4302','Pemeriksaan Akuntansi II','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('136', 'ACC4702','Metodologi Penelitian Akuntansi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('137', 'ACC4304','Audit Internal','Akuntansi Islam','2','2');
INSERT INTO `mata_kuliah` VALUES('138', 'ACC4902','Applied Database Management Systems','Akuntansi Islam','1','3');
INSERT INTO `mata_kuliah` VALUES('139', 'ACC4305','Audit Forensik','Akuntansi Islam','2','3');
INSERT INTO `mata_kuliah` VALUES('140', 'ACC4903','Decision Support Systems','Akuntansi Islam','1','2');
INSERT INTO `mata_kuliah` VALUES('141', 'ACC4306','EDP Auditing','Akuntansi Islam','2','3');
INSERT INTO `mata_kuliah` VALUES('142', 'ACC4905','Network Based Accounting Information Systems II','Akuntansi Islam','1','2');
INSERT INTO `mata_kuliah` VALUES('143', 'MKK-A-3721','Akuntansi Internasional','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('144', 'ACC4101','Skripsi','Akuntansi Islam','0','6');
INSERT INTO `mata_kuliah` VALUES('145', 'MKJ-E03','Matematika Ekonomi Lanjutan','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('146', 'MKU-B-3317','Fiqh Muamalah','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('147', 'AEM2105','Usul Fiqh I','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('148', 'ENT3601','Kewirausahaan I','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('149', 'AEM2304','Applied Statistics','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('150', 'AEM2106','Fiqh Muamalah II','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('151', 'ACC2102','Pengantar Akuntansi II','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('152', 'AEM2305','Aspek Hukum Dalam Ekonomi','Ekonomi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('153', 'AEM2108','Fiqh Mawarist','Ekonomi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('154', 'ACC2701','Etika Bisnis Islam','Ekonomi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('155', 'ECO2203','Teori Ekonomi MIkro I','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('156', 'AEM2107','Usul Fiqh II','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('157', 'AEM2204','Bahasa Inggris Akademik','Ekonomi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('158', 'AEM2109','Studi Kepemimpinan Islam','Ekonomi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('159', 'AEM2110','Fundamental Ekonomi Islam','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('160', 'MGT2201','Manajemen Keuangan','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('161', 'MKK-E-2401','Mustalahat Iqtishadiyah','Ekonomi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('162', 'ECO2201','Teori Ekonomi Makro I','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('163', 'ECO3202','Teori Ekonomi Makro II','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('164', 'AEM2303','Bank & Lembaga Keuangan','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('165', 'AEM3111','Fiqh Zakat','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('166', 'AEM3306','Lab Mini Bank Islam','Ekonomi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('167', 'ECO3401','Ekonomi Moneter','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('168', 'ECO3603','Ekonometrik I','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('169', 'ECO2204','Teori Ekonomi Mikro II','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('170', 'ECO3103','Mikro Ekonomi Islam','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('171', 'ECO3206','Sejarah Pemikiran Ekonomi','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('172', 'ECO3104','Maqoshid Syariah','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('173', 'ENT3102','Sistem Informasi Manajemen','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('174', 'ECO3602','Ekonometrik II','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('175', 'ECO3101','Makro Ekonomi Islam','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('176', 'ECO3105','Sejarah Pemikiran Ekonomi Islam','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('177', 'ECO3106','Seminar Ekonomi Islam','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('178', 'ECO3402','Keuangan Publik','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('179', 'AEM3205','Fahmul Maqruq','Ekonomi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('180', 'ECO3303','Ekonomi Pembangunan','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('181', 'ECO3102','Magang','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('182', 'ECO4602','Riset Metodologi','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('183', 'MKJ-U07','Operational Research','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('184', 'MKK-U17','Metodologi Penelitian','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('185', 'ECO4304','Perekonomian Indonesia','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('186', 'MKJ-E14','Perbandingan Sistem Ekonomi','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('187', 'ECO4302','Ekonomi Industri','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('188', 'ECO4305','Ekonomi Internasional','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('189', 'ECO4501','Islamic Capital Market','Ekonomi Islam','6','3');
INSERT INTO `mata_kuliah` VALUES('190', 'ECO4502','Islamic Monetary System','Ekonomi Islam','6','3');
INSERT INTO `mata_kuliah` VALUES('191', 'MKJ-E04','Ekonomi Mikro Lanjutan','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('192', 'ECO4503','Corporate Finance','Ekonomi Islam','6','3');
INSERT INTO `mata_kuliah` VALUES('193', 'ECO3406','Pembangunan Sdi','Ekonomi Islam','5','3');
INSERT INTO `mata_kuliah` VALUES('194', 'MKJ-U17','Teori Pengambilan Keputusan','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('195', 'ECO4101','Skripsi','Ekonomi Islam','0','6');
INSERT INTO `mata_kuliah` VALUES('196', 'BIS3205','Perilaku Konsumen','Bisnis Dan Manajemen Islam','4','3');
INSERT INTO `mata_kuliah` VALUES('197', 'ACC4302','Auditing II','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('198', 'ECO4401','Masalah Dan Kebijakan Pembangunan','Ekonomi Islam','5','3');
INSERT INTO `mata_kuliah` VALUES('199', 'ECO3106','Seminar Ekonomi Islam','Bisnis Dan Manajemen Islam','8','3');
INSERT INTO `mata_kuliah` VALUES('200', 'AEM1101','Dirasah Islamiah','Bisnis Dan Manajemen Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('201', 'AEM1201','Bahasa Inggris Ekonomi','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('202', 'AEM1202','Bahasa Indonesia','Bisnis Dan Manajemen Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('203', 'AEM1301','Matematika Ekonomi','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('204', 'MGT1207','Pengantar Bisnis dan Manajemen','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('205', 'AEM1401','Pengantar Aplikasi Komputer','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('206', 'ECO1205','Pengantar Ekonomi','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('207', 'TJA','TAHFIDZ JUZ','Bisnis Dan Manajemen Islam','0','0');
INSERT INTO `mata_kuliah` VALUES('208', 'AEM1102','Sejarah Peradaban Islam','Bisnis Dan Manajemen Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('209', 'AEM1203','Bahasa Arab Ekonomi','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('210', 'AEM1302','Metode Statistik','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('211', 'ACC1101','Pengantar Akuntansi I','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('212', 'AEM1103','Fiqh Muamalah I','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('213', 'AEM1104','Ayat & Hadits Ekonomi','Bisnis Dan Manajemen Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('214', 'AEM1105','Kewarganegaraan','Bisnis Dan Manajemen Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('215', 'AEM1101','Dirasah Islamiah','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('216', 'AEM1201','Bahasa Inggris Ekonomi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('217', 'AEM1202','Bahasa Indonesia','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('218', 'AEM1301','Matematika Ekonomi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('219', 'MGT1207','Pengantar Bisnis dan Manajemen','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('220', 'AEM1401','Teknologi Informasi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('221', 'ECO1205','Pengantar Ekonomi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('222', 'TJA','TAHFIDZ JUZ','Akuntansi Islam','0','0');
INSERT INTO `mata_kuliah` VALUES('223', 'AEM1102','Sejarah Peradaban Islam','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('224', 'AEM1203','Bahasa Arab Ekonomi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('225', 'AEM1302','Metode Statistik','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('226', 'ACC1101','Pengantar Akuntansi I','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('227', 'AEM1103','Fiqh Muamalah I','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('228', 'AEM1104','Ayat & Hadits Ekonomi','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('229', 'AEM1105','Kewarganegaraan','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('230', 'AEM1101','Dirasah Islamiah','Ekonomi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('231', 'AEM1201','Bahasa Inggris Ekonomi','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('232', 'AEM1202','Bahasa Indonesia','Ekonomi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('233', 'AEM1301','Matematika Ekonomi','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('234', 'MGT1207','Pengantar Bisnis dan Manajemen','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('235', 'AEM1401','Teknologi Informasi','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('236', 'ECO1205','Pengantar Ekonomi','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('237', 'TJA','TAHFIDZ JUZ','Ekonomi Islam','0','0');
INSERT INTO `mata_kuliah` VALUES('238', 'AEM1102','Sejarah Peradaban Islam','Ekonomi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('239', 'AEM1203','Bahasa Arab Ekonomi','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('240', 'AEM1302','Metode Statistik','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('241', 'ACC1101','Pengantar Akuntansi I','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('242', 'AEM1103','Fiqh Muamalah I','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('243', 'AEM1104','Ayat & Hadits Ekonomi','Ekonomi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('244', 'AEM1402','Kewarganegaraan','Ekonomi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('245', 'ECO3406','Pembangunan Sdi','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('246', 'ECO3603','Ekonometrik I','Bisnis Dan Manajemen Islam','8','3');
INSERT INTO `mata_kuliah` VALUES('247', 'ECO4501','Islamic Capital Market','Bisnis Dan Manajemen Islam','8','3');
INSERT INTO `mata_kuliah` VALUES('248', 'ECO4503','Corporate Finance','Bisnis Dan Manajemen Islam','8','3');
INSERT INTO `mata_kuliah` VALUES('249', 'ACC2401','Perpajakan I','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('250', 'ECO2204','Teori Ekonomi MIkro II','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('251', 'ECO3104','Maqoshid Syariah','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('252', 'ECO3202','Teori Ekonomi Makro II','Bisnis Dan Manajemen Islam','8','3');
INSERT INTO `mata_kuliah` VALUES('253', 'ECO3401','Ekonomi Moneter','Bisnis Dan Manajemen Islam','8','3');
INSERT INTO `mata_kuliah` VALUES('254', 'ECO3106','Seminar Ekonomi Islam','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('255', 'ECO3406','Pembangunan Sdi','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('256', 'ECO3603','Ekonometrik I','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('257', 'ECO4501','Islamic Capital Market','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('258', 'ECO4503','Corporate Finance','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('259', 'MKT3502','Pemasaran Internasional','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('260', 'BIS3205','Perilaku Konsumen','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('261', 'FIN4304','Seminar Keuangan & Perbankan','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('262', 'FIN4305','Manajemen Resiko Keuangan','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('263', 'ECO2201','Teori Ekonomi Makro I','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('264', 'ECO2203','Teori Ekonomi Mikro I','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('265', 'BIS4206','Studi Kelayakan Bisnis','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('266', 'ACC2401','Perpajakan I','Ekonomi Islam','10','3');
INSERT INTO `mata_kuliah` VALUES('267', 'MKT3502','Pemasaran Internasional','Ekonomi Islam','10','3');
INSERT INTO `mata_kuliah` VALUES('268', 'BIS3205','Perilaku Konsumen','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('269', 'FIN4304','Seminar Keuangan & Perbankan','Ekonomi Islam','10','3');
INSERT INTO `mata_kuliah` VALUES('270', 'FIN4305','Manajemen Resiko Keuangan','Ekonomi Islam','10','3');
INSERT INTO `mata_kuliah` VALUES('271', 'ACC3501','Akuntansi Lembaga Keuangan Syariah','Ekonomi Islam','10','3');
INSERT INTO `mata_kuliah` VALUES('272', 'ACC3601','Akuntansi Zakat','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('273', 'MGT3103','Manajemen Investasi','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('274', 'FIN3302','Manajemen Keuangan Lanjutan','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('275', 'BIS3202','Bisnis Internasional','Ekonomi Islam','10','3');
INSERT INTO `mata_kuliah` VALUES('276', 'MGT3301','Manajemen Pemasaran','Ekonomi Islam','10','3');
INSERT INTO `mata_kuliah` VALUES('277', 'IFI3401','Manajemen Perbankan Islam I','Ekonomi Islam','10','3');
INSERT INTO `mata_kuliah` VALUES('278', 'IFI3402','Manajemen Lks','Ekonomi Islam','10','3');
INSERT INTO `mata_kuliah` VALUES('279', 'BIS3203','Manajemen Operasi','Ekonomi Islam','10','3');
INSERT INTO `mata_kuliah` VALUES('280', 'BIS3204','Perilaku Organisasi','Ekonomi Islam','10','3');
INSERT INTO `mata_kuliah` VALUES('281', 'ECO3401','Ekonomi Moneter','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('282', 'MGT3103','Manajemen Investasi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('283', 'FIN3302','Manajemen Keuangan Lanjutan','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('284', 'BIS3202','Bisnis Internasional','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('285', 'MGT3301','Manajemen Pemasaran','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('286', 'IFI3401','Manajemen Perbankan Islam I','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('287', 'IFI3403','Manajemen Keuangan Islam','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('288', 'IFI3402','Manajemen Lks','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('289', 'BIS3203','Manajemen Operasi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('290', 'BIS3204','Perilaku Organisasi','Akuntansi Islam','9','3');
INSERT INTO `mata_kuliah` VALUES('291', 'ECO4301','Masalah dan Kebijakan Ekonomi','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('292', 'AEM1205','Ushul Fiqh 1','Bisnis Dan Manajemen Islam','3','3');
INSERT INTO `mata_kuliah` VALUES('293', 'DPL1101','Dirasah Islamiah','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('294', 'DPL1102','Bahasa Inggris Ekonomi','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('295', 'DPL1103','Bahasa Arab 1','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('296', 'DPL1201','Pengantar Bisnis dan Manajemen','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('297', 'DPL1113','Pengantar Ekonomi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('298', 'DPL1301','Lembaga Keuangan Mikro Syariah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('299', 'DPL1104','Kewarganegaraan','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('300', 'DPL1105','Matematika Ekonomi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('301', 'DPL1106','Bahasa Arab 2','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('302', 'DPL1107','Fiqh Muamalah 1','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('303', 'DPL1108','Bahasa Indonesia','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('304', 'DPL1109','Fundamental Ekonomi Islam','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('305', 'DPL1302','Dasar Usaha Mikro Kecil dan Menengah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('306', 'DPL1110','Aplikasi Komputer','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('307', 'DPL1401','Pengantar Akuntansi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('308', 'DPL1111','Pengantar Statistika','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('309', 'DPL1112','Ayat dan Hadist Ekonomi','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('310', 'DPL2114','Kepemimpinan Islam','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('311', 'DPL2303','Manajemen Keuangan Mikro Syariah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('312', 'DPL2202','Manajemen Pemasaran','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('313', 'DPL2203','Sistem Informasi Manajemen','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('314', 'DPL2204','Kewirausahaan','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('315', 'DPL2115','Ushul Fiqh','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('316', 'DPL2402','Akuntansi Lembaga Keuangan Mikro Syariah 1','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('317', 'DPL2304','Aspek Hukum dalam Lembaga Keuangan Mikro Syariah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('318', 'DPL2205','Penganggaran','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('319', 'DPL2116','Fiqh Muamalah 2','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('320', 'DPL2305','Dasar-Dasar Koperasi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('321', 'DPL2306','Manajemen Lembaga Keuangan Mikro Syariah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('322', 'DPL2206','Manajemen Risiko','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('323', 'DPL2207','Manajemen Sumber Daya Insani','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('324', 'DPL2307','Produk Lembaga Keuangan Mikro Syariah','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('325', 'DPL2308','Lab mini BPRS','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('326', 'DPL3309','Analisa Laporan Keuangan Lembaga Keuangan Mikro Syariah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('327', 'DPL3403','Audit Lembaga Keuangan Mikro Syariah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('328', 'DPL3404','Praktikum Akuntansi Lembaga Keuangan Mikro Syariah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('329', 'DPL3405','Akuntansi Lembaga Keuangan Mikro Syariah 2','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('330', 'DPL3406','Perpajakan','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('331', 'DPL3210','Perilaku Organisasi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('332', 'DPL3118','Tugas Akhir','Manajemen Keuangan Mikro Syariah','0','4');
INSERT INTO `mata_kuliah` VALUES('333', 'DPL3117','Magang','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('334', 'MKK-600','Akuntansi Manajemen Strategik','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('335', 'MKD-505','Manajemen Risiko Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('336', 'MKD-504','Manajemen Investasi Islam','Magister Ekonomi Syariah','9','3');
INSERT INTO `mata_kuliah` VALUES('337', 'MKK-503','Teori Uang dan Perbankan','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('338', 'MKK-502','Kepemilikan dan Distribusi Harta dalam Islam','Magister Ekonomi Syariah','9','3');
INSERT INTO `mata_kuliah` VALUES('339', 'MKK-501','Pasar Keuangan Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('340', 'MKK-500','Manajemen Kekayaan Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('341', 'MKD-407','Restrukturisasi','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('342', 'MKD-406','Manajemen Stratejik Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('343', 'MKD-405','Derifatif Keuangan Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('344', 'MKD-404','Manajemen Lembaga Keuangan Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('345', 'MKK-403','Manajemen Operasi','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('346', 'MKK-402','Manajemen Sumber Daya Insani','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('347', 'MKK-401','Manajemen Pemasaran Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('348', 'MKK-400','Manajemen Keuangan Islam','Magister Ekonomi Syariah','8','3');
INSERT INTO `mata_kuliah` VALUES('349', 'MKD-307','Ushul Fiqh dan Maqashid Syariah','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('350', 'MKD-306','Filsafat dan Pemikiran Ekonomi Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('351', 'MKD-304','Metode Penelitian','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('352', 'MKD-301','Ekonomi Makro Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('353', 'MKD-305','Ekonometrika','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('354', 'MKD-303','Tata Kelola dan Etika Bisnis Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('355', 'MKD-302','Fiqh Muamalah','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('356', 'MKD-300','Ekonomi Mikro Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('357', 'MKK-601','Sistem Informasi Akuntansi','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('358', 'MKK-602','Praktik dan Isu Auditing','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('359', 'MKK-603','Akuntansi Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('360', 'MKD-604','Standar dan Pedoman Akuntansi Islam','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('361', 'MKD-605','Analisis Laporan Keuangan','Magister Ekonomi Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('362', 'MGT4105','Manajemen Strategi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('363', 'AEM1101','Dirasah Islamiyah','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('364', 'AEM1201','Bahasa Inggris Ekonomi','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('365', 'AEM1202','Bahasa Indonesia','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('366', 'AEM1301','Matematika ekonomi','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('367', 'MGT1207','Pengantar Bisnis & Manajemen','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('368', 'AEM1401','Teknologi Informasi','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('369', 'ECO1205','Pengantar Ekonomi','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('370', 'AEM1102','Sejarah Peradaban Islam','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('371', 'AEM1203','Bahasa Arab ekonomi','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('372', 'AEM1302','Metode Statistik','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('373', 'ACC1101','Pengantar Akuntansi I','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('374', 'AEM1103','Fiqih Mualamah I','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('375', 'AEM1104','Ayat & Hadits ekonomi','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('376', 'AEM1401','Kewarganegaraan','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('377', 'AEM2105','Ushul Fiqih I','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('378', 'MUA0601','Hukum Bisnis Islam','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('379', 'LAW2201','Ayat & Hadist Ekonomi Lanjutan','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('380', 'AEM2304','Applied Statistics','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('381', 'ACC2701','Etika Bisnis Islam','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('382', 'AEM2108','Fiqih Mawarist','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('383', 'MUA0604','Qaidah Fiqhiyah I','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('384', 'AEM2107','Ushul Fiqh II','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('385', 'AEM2110','Fundamental Ekonomi Islam','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('386', 'AEM2111','Fiqh Zakat','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('387', 'MUA0605','Fiqh Muamalat Kontemporer','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('388', 'MUA0606','Sosiologi Hukum Islam','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('389', 'MGT2201','Manajemen Keuangan','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('390', 'MUA0607','Hukum Asuransi Islam','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('391', 'MUA0608','Hukum Perbankan Islam','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('392', 'MUA0609','Qaidah Fiqhiyah II','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('393', 'MUA0610','Hukum Zakat dan Wakaf di Indonesia','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('394', 'ENT3601','Enterpreneurship','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('395', 'MUA0611','Hukum Perdata','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('396', 'MUA0612','Hukum Investasi','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('397', 'LAW3303','Pemikiran Modern Hukum Islam','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('398', 'MUA0613','Hukum Pasar Modal Syariah','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('399', 'MUA0614','Seminar isu-isu Muamalat','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('400', 'LAW4311','Penyelesaian Sengketa Alternatif (ADR)','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('401', 'MUA0616','Hukum Hak Milik Intelektual dan Hak Cipta','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('402', 'LAW3115','Hukum Keluarga Islam','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('403', 'MUA0617','Business Legal Contract','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('404', 'ECO3104','Maqoshid Syariah','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('405', 'MUA0618','Legal Drafting','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('406', 'LAW3306','Hukum Organisasi Perusahaan','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('407', 'MUA0619','Usul Fiqih III (ekonomi Islam)','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('408', 'MUA0620','Peradilan Islam dan Praktik Peradilan di Indonesia','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('409', 'MUA0621','Tindak Pidana Ekonomi','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('410', 'MUA0622','Fatwa Bisnis Syariah','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('411', 'MUA0623','Pemberdayaan Masyarakat','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('412', 'MUA0624','Filsafat Hukum Islam','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('413', 'MUA0625','Metode Penelitian Hukum Ekonomi Islam','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('414', 'MUA0626','Studi Naskah Hukum Bisnis Islam','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('415', 'MUA0629','Hukum Surat-surat Berharga','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('416', 'MUA0630','Fiqh Peradilan (Qhadha)','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('417', 'MUA0632','Hukum Pajak','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('418', 'MUA0635','Tafsir ayat-ayat Ahkam','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('419', 'MUA0637','Fiqh Daulah / Siasat Syariah','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('420', 'MUA0638','Hukum Perdata Internasional','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('421', 'MUA0639','Tarikh Tasyri','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('422', 'MUA0627','Magang','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('423', 'MUA0628','Skripsi','Hukum Ekonomi Syariah (Muamalat)','0','6');
INSERT INTO `mata_kuliah` VALUES('424', '','','','0','0');
INSERT INTO `mata_kuliah` VALUES('425', 'DPL3209','Manajemen Perkantoran dan Administrasi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('426', 'DPL3311','Pricing','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('427', 'DPL3310','Pengarsipan','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('428', 'DPL3308','Praktek Operasi Lembaga Keuangan Mikro Syariah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('429', 'ACC2103','Akuntansi Keuangan I','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('430', 'ECO3104','Maqoshid Syariah','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('431', 'ACC3502','Pajak','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('432', 'ACC3811','Algorithm and Data Structure on Sharia Compliance','Akuntansi Islam','11','5');
INSERT INTO `mata_kuliah` VALUES('433', 'ACC3815','Computer Network','Akuntansi Islam','11','4');
INSERT INTO `mata_kuliah` VALUES('434', 'ACC3812','Database Introduction','Akuntansi Islam','11','3');
INSERT INTO `mata_kuliah` VALUES('435', 'ACC3813','Management Information System','Akuntansi Islam','11','3');
INSERT INTO `mata_kuliah` VALUES('436', 'ACC3814','Sharia Banking Information Technology','Akuntansi Islam','11','4');
INSERT INTO `mata_kuliah` VALUES('437', 'ACC3816','Database Administration','Akuntansi Islam','11','3');
INSERT INTO `mata_kuliah` VALUES('438', 'ACC3804','Decission Support System','Akuntansi Islam','11','2');
INSERT INTO `mata_kuliah` VALUES('439', 'ACC3817','Object Oriented Programming','Akuntansi Islam','11','3');
INSERT INTO `mata_kuliah` VALUES('440', 'ACC3505','Sharia Banking Funding Products and Services','Akuntansi Islam','11','3');
INSERT INTO `mata_kuliah` VALUES('441', 'ACC3819','Software Engineering','Akuntansi Islam','11','3');
INSERT INTO `mata_kuliah` VALUES('442', 'ACC4819','Advanced Programming','Akuntansi Islam','11','0');
INSERT INTO `mata_kuliah` VALUES('443', 'ACC4820','Rapid Application Development with Sharia Complian','Akuntansi Islam','11','0');
INSERT INTO `mata_kuliah` VALUES('444', 'ACC4506','Sharia Banking Financing Products','Akuntansi Islam','11','0');
INSERT INTO `mata_kuliah` VALUES('445', 'ACC4822','Web Programming for Sharia Compliance','Akuntansi Islam','11','0');
INSERT INTO `mata_kuliah` VALUES('446', 'ACC4826','Information System Project Management','Akuntansi Islam','11','0');
INSERT INTO `mata_kuliah` VALUES('447', 'ACC4825','XML and Web Service','Akuntansi Islam','11','0');
INSERT INTO `mata_kuliah` VALUES('448', 'LAW3210','Hadits Ahkam','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('449', 'SDS3035','Student Dynamic Session','Bisnis Dan Manajemen Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('450', 'AEM2303','Bank & Lembaga Keuangan Islam','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('451', 'ENT 2601','Kewirausahaan I','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('452', 'IFI 3305','Manajemen Asuransi Syariah','Bisnis Dan Manajemen Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('453', 'FIN 4306','Analisa Pembiayaan','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('454', 'ENT 3303','Entrepreneurship II','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('455', 'ECO2304','Ekonometrika Dasar','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('456', 'AEM 2111','Fiqh Muamalah III','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('457', 'ACC2304','Ekonometrika Dasar','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('458', 'SDS3003','Student Dynamic Session','Akuntansi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('459', 'ACC3602','Sistem Informasi Enterprise','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('460', 'ACC4207','Seminar Akuntansi Keuangan','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('461', 'ACC4605','Knowledge Management System','Akuntansi Islam','1','3');
INSERT INTO `mata_kuliah` VALUES('462', 'ACC4606','Data Mining','Akuntansi Islam','1','3');
INSERT INTO `mata_kuliah` VALUES('463', 'ACC4208','Best Practice In Accounting','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('464', 'ACC4405','Auditing Internal','Akuntansi Islam','2','2');
INSERT INTO `mata_kuliah` VALUES('465', 'ACC3502','Pajak','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('466', 'SDS3031','Student Dynamic Session','Ekonomi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('467', 'FIN 4306','Analisa Pembiayaan','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('468', 'LAW3303','Pemikiran Modern Hukum Islam','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('469', 'SDS0005','Student Dynamics Session V','Hukum Ekonomi Syariah (Muamalat)','0','1');
INSERT INTO `mata_kuliah` VALUES('470', 'MKT-700','Tesis','Magister Ekonomi Syariah','0','6');
INSERT INTO `mata_kuliah` VALUES('471', 'LAW3400','Islamic Financial Planner I','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('472', 'LAW3401','Islamic Financial Planner II','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('473', 'LAW4403','Pengantar Hukum Indonesia','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('474', 'LAW4404','Hukum Perikatan','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('475', 'LAW3404','Hukum Acara Perdata dan PA','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('476', 'ACC3801','Lab Akuntansi','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('477', 'ACC 3203','Cost & Management Accounting','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('478', 'DPL-O.03.02','UMKM dan Perkoperasian','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('479', 'DPL-O.03.03','Manajemen LKS','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('480', 'MKD-401','Keuangan dan Perbankan Islam','Magister Ekonomi Syariah','8','3');
INSERT INTO `mata_kuliah` VALUES('481', 'ECO3105','Sejarah Pemikiran Ekonomi Islam','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('482', 'ECO3402','Keuangan Publik','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('483', 'FIN4104','Manajemen Sumber Daya Insani','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('484', 'ECO3402','Keuangan Publik','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('485', 'MUA0614','Seminar isu-isu Muamalat','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('486', 'MGT3101','Metode Penelitian Bisnis','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('487', 'MUA0603','Bank dan Keuangan Islam','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('488', 'ACC2201','Akuntansi Biaya','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('489', 'ECO4703','Islamic Wealth Management','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('490', 'ECO4703','Islamic Wealth Management','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('491', 'ACC2502','Accounting for Islamic Banks I','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('492', 'ENT4603','Entrepreneurship III','Bisnis Dan Manajemen Islam','4','3');
INSERT INTO `mata_kuliah` VALUES('493', 'ACC4306','EDP Auditing','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('494', 'DPL-O.03.01','Pengantar Bisnis Manajemen','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('495', 'DPL-U.01.01','Matematika Ekonomi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('496', 'ACC4402','Auditing II','Akuntansi Islam','2','2');
INSERT INTO `mata_kuliah` VALUES('497', 'DPL-T.02.02','Dirasah Islamiyah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('498', 'DPL-T.02.01','Pengantar Ekonomi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('499', 'DPL-U.01.02','Bahasa Indonesia','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('500', 'DPL-O.03.13','Aplikasi Komputer','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('501', 'ACC4404','Audit Forensik','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('502', 'ACC4403','EDP Audit','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('503', 'ACC4108','Akuntansi Islam','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('504', 'MUA0612','Hukum Investasi','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('505', 'ECO4305','Islamic Wealth Management','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('506', 'AEM2306','Applied Statistics','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('507', 'DPL2117','Ushul Fiqh 2','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('508', 'DPL2208','Kewirausahaan 2','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('509', 'DPL2209','UMKM dan Perkoperasian','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('510', 'SDS3004','Student Dynamic Session','Akuntansi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('511', 'SDS4005','Student Dynamic Session V','Akuntansi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('512', 'SDS3036','Student Dynamic Session','Bisnis Dan Manajemen Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('513', 'SDS0005','Student Dynamic Session V','Bisnis Dan Manajemen Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('514', 'SDS3032','Student Dynamic Session','Ekonomi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('515', 'SDS0005','Student Dynamic Session V','Ekonomi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('516', 'SDS3039','Student Dynamic Session','Hukum Ekonomi Syariah (Muamalat)','0','1');
INSERT INTO `mata_kuliah` VALUES('517', 'SDS3030','Student Dynamic Session','Hukum Ekonomi Syariah (Muamalat)','0','1');
INSERT INTO `mata_kuliah` VALUES('518', 'SDS20142','Student Dynamic Session','Bisnis Dan Manajemen Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('519', 'SDS20142','Student Dynamic Session','Akuntansi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('520', 'SDS20142','Student Dynamic Session','Ekonomi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('521', 'SDS20142','Student Dynamic Session','Hukum Ekonomi Syariah (Muamalat)','0','1');
INSERT INTO `mata_kuliah` VALUES('522', 'SDS20134','Student Dynamic Session','Hukum Ekonomi Syariah (Muamalat)','0','1');
INSERT INTO `mata_kuliah` VALUES('523', 'SDS20134','Student Dynamic Session','Bisnis Dan Manajemen Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('524', 'SDS20134','Student Dynamic Session','Akuntansi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('525', 'SDS20134','Student Dynamic Session','Ekonomi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('526', 'ACC2502','Accounting For Islamic Banks I','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('527', 'ACC2306','Basic Auditing For Islamic Financial','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('528', 'ACC2109','Financial Statment Analysis','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('529', '0','Tahfidz dan Takhsin','Magister Ekonomi Syariah','0','0');
INSERT INTO `mata_kuliah` VALUES('530', 'ACC2204','Cost Management','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('531', 'ACC2601','Akuntansi Zakat','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('532', 'DPL1136','Bahasa Arab Ekonomi','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('533', 'ACC2504','Accounting for Islamic Banks II','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('534', 'SDS0001','Student Dynamic Session I','Ekonomi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('535', 'SDS0001','Student Dynamic Session I','Akuntansi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('536', 'SDS0002','Student Dynamic Session II','Akuntansi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('537', 'SDS0003','Student Dynamic Session III','Akuntansi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('538', 'SDS0004','Student Dynamic Session IV','Akuntansi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('539', 'SDS0001','Student Dynamic Session I','Bisnis Dan Manajemen Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('540', 'SDS0002','Student Dynamic Session','Bisnis Dan Manajemen Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('541', 'SDS0003','Student Dynamic Session III','Bisnis Dan Manajemen Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('542', 'SDS0004','Student Dynamic Session IV','Bisnis Dan Manajemen Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('543', 'SDS0002','Student Dynamic Session','Ekonomi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('544', 'SDS0003','Student Dynamic Session III','Ekonomi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('545', 'SDS0004','Student Dynamic Session IV','Ekonomi Islam','0','1');
INSERT INTO `mata_kuliah` VALUES('546', 'SDS0001','Student Dynamic Session I','Hukum Ekonomi Syariah (Muamalat)','0','1');
INSERT INTO `mata_kuliah` VALUES('547', 'SDS0002','Student Dynamic Session','Hukum Ekonomi Syariah (Muamalat)','0','1');
INSERT INTO `mata_kuliah` VALUES('548', 'SDS0003','Student Dynamic Session III','Hukum Ekonomi Syariah (Muamalat)','0','1');
INSERT INTO `mata_kuliah` VALUES('549', 'SDS0004','Student Dynamic Session IV','Hukum Ekonomi Syariah (Muamalat)','0','1');
INSERT INTO `mata_kuliah` VALUES('550', 'TLC01','Bahasa Inggris','Matrikulasi','0','0');
INSERT INTO `mata_kuliah` VALUES('551', 'TLC03','Bahasa Inggris','Matrikulasi','0','0');
INSERT INTO `mata_kuliah` VALUES('552', 'TLC02','Bahasa Arab','Matrikulasi','0','0');
INSERT INTO `mata_kuliah` VALUES('553', 'TLC04','Bahasa Arab','Matrikulasi','0','3');
INSERT INTO `mata_kuliah` VALUES('554', 'ACC2103','Akuntansi Keuangan I','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('555', 'BIS3205','Perilaku Konsumen','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('556', 'DPL-O 03.01','Pengantar Bisnis & Manajemen','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('557', 'DPL-U 01.01','Matematika Ekonomi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('558', 'DPL-T 02.01','Pengantar Ekonomi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('559', 'DPL-O 03.13','Aplikasi Komputer','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('560', 'DPL-T 02.02','Dirasah Islamiah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('561', 'DPL-U 01.02','Bahasa Indonesia','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('562', 'DPL-O 03.02','UMKM & Perkoperasian','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('563', 'DPL-O 03.15','Statistika','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('564', 'DPL-A 05.01','Pengantar Akuntansi  1','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('565', 'DPL-U 01.03','Bahasa Inggris Ekonomi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('566', 'DPL-O 03.14','Bahasa Arab Ekonomi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('567', 'DPL-T 02.03','Ushul Fiqih','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('568', 'DPL-T 02.04','Ayat Hadis Ekonomi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('569', 'DPL-O 03.03','Manajemen LKS','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('570', 'DPL-O 03.04','Manajemen Keuangan Mikro Syariah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('571', 'DPL-O 03.05','Aspek Hukum LKS','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('572', 'DPL-U 01.04','Pendidikan Kewarganegaraan','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('573', 'DPL-T 02.05','Fundamental Ekonomi Islam','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('574', 'DPL-A 05.02','Pengantar Akuntansi  2','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('575', 'DPL-T 02.06','Fiqh Muamalah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('576', 'DPL-P 04.01','Enterpreneurship','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('577', 'DPL-O 03.06','Manajemen Sumber Daya Insani','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('578', 'DPL-O 03.07','Perilaku Organisasi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('579', 'DPL-A 05.03','Akuntansi KMS 1','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('580', 'DPL-P 04.02','Manajemen Pemasaran Jasa','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('581', 'DPL-O 03.08','Praktek Operasi KMS Bank','Manajemen Keuangan Mikro Syariah','0','4');
INSERT INTO `mata_kuliah` VALUES('582', 'DPL-O 03.09','Analisa Pembiayaan','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('583', 'DPL-P 04.03','Perilaku Pelanggan','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('584', 'DPL-P 04.04','Pengembangan Produk','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('585', 'DPL-A 05.04','Akuntansi KMS 2','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('586', 'DPL-T 02.07','Pemberdayaan Ekonomi Masyarakat','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('587', 'DPL-O 03.10','Praktek Operasi KMS Non Bank','Manajemen Keuangan Mikro Syariah','0','4');
INSERT INTO `mata_kuliah` VALUES('588', 'DPL-P 04.05','Penanganan Pembiayaan Bermasalah','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('589', 'DPL-A 05.05','Perpajakan','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('590', 'DPL-P 04.06','Customer Relationship Management (CRM)','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('591', 'DPL-P 04.07','Metodologi Survey','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('592', 'DPLA 05.06','Praktik Software Akuntansi','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('593', 'DPL-O 03.11','Magang','Manajemen Keuangan Mikro Syariah','0','5');
INSERT INTO `mata_kuliah` VALUES('594', 'DPL-O 03.12','Tugas Akhir','Manajemen Keuangan Mikro Syariah','0','3');
INSERT INTO `mata_kuliah` VALUES('595', 'DPL-T 02.08','Prophetic Leadership & Management Rasulullah SAW','Manajemen Keuangan Mikro Syariah','0','2');
INSERT INTO `mata_kuliah` VALUES('596', 'ACC3805','Enterprise Resource Planning','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('597', 'AEM3306','Lab Mini Bank Islam','Hukum Ekonomi Syariah (Muamalat)','0','2');
INSERT INTO `mata_kuliah` VALUES('598', 'AEM2106','Fiqh Muamalah II','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('599', 'MUA0604','Qaedah Fiqhiyah I','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('600', 'MUA0604','Qaedah Fiqhiyah I','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('601', 'MKT4504','Komunikasi Pemasaran','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('602', 'ECO3206','Sejarah Pemikiran Ekonomi','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('603', 'LAW3210','Hadits Ahkam','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('604', 'MUA0613','Hukum Pasar Modal Syariah','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('605', 'FIN4306','Analisa Pembiayaan','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('606', 'ECO3206','Sejarah Pemikiran Ekonomi','Akuntansi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('607', 'ECO4302','Ekonomi Industri','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('608', 'MKT4504','Komunikasi Pemasaran','Hukum Ekonomi Syariah (Muamalat)','0','3');
INSERT INTO `mata_kuliah` VALUES('609', 'ACC4605','Knowledge Management System','Bisnis Dan Manajemen Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('610', 'MUA0622','Fatwa Bisnis Syariah','Bisnis Dan Manajemen Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('611', 'MKT4504','Komunikasi Pemasaran','Ekonomi Islam','0','3');
INSERT INTO `mata_kuliah` VALUES('612', 'ACC3806','Oracle I','Akuntansi Islam','1','3');
INSERT INTO `mata_kuliah` VALUES('613', 'LAW3115','Hukum Keluarga Islam','Akuntansi Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('614', 'LAW3115','Hukum Keluarga Islam','Bisnis Dan Manajemen Islam','0','2');
INSERT INTO `mata_kuliah` VALUES('615', 'ACC3818','Information Security System','Akuntansi Islam','0','2');