INSERT INTO m_jenis_pengajuan_dokumen (id, keterangan, nama, required) VALUES
('1','JPG/PDF','File Surat Pengantar dari Pimpinan PT',true),
('2','JPG/PDF','File Ijasah (Disertai Akreditasi Prodi; Penyetaraan Ijazah (untuk lulusan luar negeri))',true),
('3','PDF','File Ringkasan Disertai/Tesis (sesuai pendidikan terakhir',true),
('4','JPG/PDF','File Surat Bebas Tugas (Bila Ada)',false),
('5','JPG/PDF','File Surat Pengaktifan Kembali (Bila Ada)',false),
('6','JPG/PDF','File Rekap DUPAK (keseluruhan)',true),
('8','JPG/PDF','File SK PAK Sebelumnya',true),
('9','JPG/PDF','File SK Jabatan Terakhir',true),
('10','PDF','File PPKP (DP3) 2 Tahun Terakhir',true),
('11','JPG/PDF','File SK Pangkat Terakhir',true),
('12','JPG/PDF','File Surat Keterangan Melaksanakan Penelitian',true),
('15','JPG/PDF','File Persetujuan/Pertimbangan Senat',true),
('16','JPG/PDF','File Daftar Hadir Anggota Senat PT',true),
('17','JPG/PDF','File Surat Pernyataan Pengesahan hasil Validasi Karya Ilmiah',true),
('18','JPG/PDF','File Surat Pernyataan Keabsahan Karya Ilmiah',true),
('19','JPG/PDF','File Sertifikat Pendidik',true),
('20','PDF','File Peer Review Per Unsur/Artikel Ilmiah/Dokumen/Buku berkaitan dengan No.21',true),
('21','Excel/Word','Daftar Profil Penelitian (Judul,ISBN,Penerbit,jml.halaman) dan Link Buku/dokumen/Penelitian',true);
